[build-system]
requires = ["scikit-build-core", "swig", "numpy<2", "scipy", "conan"]
build-backend = "scikit_build_core.build"

[project]
name = "medcoupling"
version = "10.0.0"
requires-python = ">= 3.8"
dependencies = ["numpy<2", "scipy"]

[tool.scikit-build]
build.verbose = true
logging.level = "INFO"
build-dir = "build/{wheel_tag}"

[tool.scikit-build.cmake.define]
CMAKE_PROJECT_TOP_LEVEL_INCLUDES = "ext/cmake-conan/conan_provider.cmake"
CMAKE_POSITION_INDEPENDENT_CODE = true
CONAN_INSTALL_ARGS = "--build=missing;--options=*:shared=False"

[dependency-groups]
dev = [
    "cibuildwheel>=2.23.2",
    "pytest>=8.3.5",
    "mpi4py"
]
# CMAKE_INSTALL_RPATH_USE_LINK_PATH = "ON"
# BUILD_SHARED_LIBS = "ON"
[tool.cibuildwheel]
before-all = [
    "uname -a",
    "bash {package}/.github/scripts/conan-ci-setup.sh",
    "sudo apt update",
    "sudo apt install -y libopenmpi-dev"
]
test-requires = "pytest mpi4py"
test-command = "pytest {project}"
