name: Continuous Integration for Windows

on:
  push:
    branches:
    - master
    - dev_v10

  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        os: [windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with: { python-version: "3.10" }

    - name: Conan cache
      uses: actions/cache@v4
      with:
        path: conan_cache_save.tgz
        key: conan-${{ matrix.os }}-${{ hashFiles('conan*.[pl][yo]*') }}

    - name: Install dependencies
      shell: bash
      run: bash < .github/scripts/conan-ci-setup.sh

    - name: Configure multi-config generator
      shell: bash
      run: cmake --preset=ci-windows

    - name: Build
      shell: bash
      run: cmake --build --preset=ci-windows

    - name: Test
      shell: bash
      run: ctest --preset=ci-windows || echo $(ls -R .); cd build && find . -name UnitTestsResult | xargs cat ; cd ..
