name: Continuous Integration

on:
  push:
    branches:
    - master
    - dev_v10

  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with: { python-version: "3.10" }

    - name: Conan cache
      uses: actions/cache@v4
      with:
        path: conan_cache_save.tgz
        key: conan-${{ matrix.os }}-${{ hashFiles('conan*.[pl][yo]*') }}

    - name: Install dependencies
      shell: bash
      run: bash < .github/scripts/conan-ci-setup.sh

    - name: Configure
      shell: pwsh
      run: cmake "--preset=ci-$("${{ matrix.os }}".split("-")[0])"

    - name: Debug Windows
      if: ${{ matrix.os == 'windows-2019' }}
      shell: pwsh
      run: cmake --build  --preset="ci-$("${{ matrix.os }}".split("-")[0])" --target genexdebug1 genexdebug2 genexdebug3

    - name: Build
      shell: pwsh
      run: cmake --build --preset="ci-$("${{ matrix.os }}".split("-")[0])"

    - name: Test
      shell: bash
      run: distrib=${{ matrix.os }} ; ctest --preset=ci-${distrib%-*} || build && find . -name UnitTestsResult | xargs cat
